import { Component, OnInit } from '@angular/core';
import { FormControl, FormGroup, Validators, FormBuilder, FormArray, Form } from '@angular/forms';

@Component({
  selector: 'app-eggdonation',
  templateUrl: './eggdonation.component.html',
  styleUrls: ['./eggdonation.component.css']
})
export class EggdonationComponent implements OnInit {

  showForm: boolean = true;

  form: FormGroup = new FormGroup ({
    firstName: new FormControl('', Validators.required),
    lastName: new FormControl('', Validators.required),
    streetAdd: new FormControl('', Validators.required),
    city: new FormControl('', Validators.required),
    state: new FormControl(0, Validators.required),
    outside_USA: new FormControl('', Validators.required),
    city_country_residence: new FormControl('', Validators.required),
    zip_code: new FormControl('', Validators.required),
    telephone_number: new FormControl('', Validators.required),
    email: new FormControl('', Validators.required),
    contact_method: new FormControl(0, Validators.required),
    others_contact_method: new FormControl('', Validators.required),
    birthDate: new FormControl('', Validators.required),
    age: new FormControl('', Validators.required),
    reason_egg_donor: new FormControl('', Validators.required),
    active_donor: new FormControl('', Validators.required),
    experience: new FormControl(0, Validators.required),
    times_donated_eggs: new FormControl(0, Validators.required),
    race: new FormControl('', Validators.required),
    registered_BIA: new FormControl(0, Validators.required),
    height: new FormControl('', Validators.required),
    weight: new FormControl('', Validators.required),
    bmi: new FormControl('', Validators.required),
    eye_color: new FormControl(0, Validators.required),
    hair_color: new FormControl(0, Validators.required),
    bodyType: new FormControl(0, Validators.required),
    other_bodyType: new FormControl('', Validators.required),
    hairType: new FormControl(0, Validators.required),
    other_hairType: new FormControl('', Validators.required),
    complexion: new FormControl(0, Validators.required),
    other_complexion: new FormControl('', Validators.required),
    dominant_hand: new FormControl(0, Validators.required),
    freckles: new FormControl(0, Validators.required),
    bloodType: new FormControl(0, Validators.required),
    highest_level_education: new FormControl(0, Validators.required),
    highSchool_name: new FormControl('', Validators.required),
    university_name: new FormControl('', Validators.required),
    highSchool_GPA: new FormControl('', Validators.required),
    university_GPA: new FormControl('', Validators.required),
    highSchool_major: new FormControl('', Validators.required),
    university_major: new FormControl('', Validators.required),
    highSchool_degree: new FormControl('', Validators.required),
    university_degree: new FormControl('', Validators.required),
    other_major: new FormControl('', Validators.required),
    other_degree: new FormControl('', Validators.required),
    strongest_subjects: new FormControl('', Validators.required),
    weakest_subjects: new FormControl('', Validators.required),
    awards: new FormControl('', Validators.required),
    country_birth: new FormControl('', Validators.required),
    marital_status: new FormControl(0, Validators.required),
    personality: new FormControl('', Validators.required),
    schedule_flexible: new FormControl('', Validators.required),
    career_goals: new FormControl('', Validators.required),
    languages_speak: new FormControl('', Validators.required),
    musical_talent: new FormControl('', Validators.required),
    artistic_talent: new FormControl('', Validators.required),
    athletic_talent: new FormControl('', Validators.required),
    hobbies: new FormControl('', Validators.required),
    vision: new FormControl(0, Validators.required),
    following: new FormControl(0, Validators.required),
    teeth: new FormControl(0, Validators.required),
    periodontal_work: new FormControl(0, Validators.required),
    hearing: new FormControl(0, Validators.required),
    baldness: new FormControl(0, Validators.required),
    baldness_family: new FormControl(0, Validators.required),
    graying: new FormControl(0, Validators.required),
    under_physicians: new FormControl(0, Validators.required),
    psychiatrist: new FormControl(0, Validators.required),
    yes_psychiatrist: new FormControl('', Validators.required),
    medications: new FormControl(0, Validators.required),
    past_illness: new FormControl(0, Validators.required),
    yes_past_illness: new FormControl('', Validators.required),
    anesthesia: new FormControl(0, Validators.required),
    yes_anesthesia: new FormControl('', Validators.required),
    blood_transfusion: new FormControl(0, Validators.required),
    yes_blood_transfusion: new FormControl('', Validators.required),
    refused_blood_donor: new FormControl(0, Validators.required),
    yes_refused_blood_donor: new FormControl('', Validators.required),
    allergies: new FormControl(0, Validators.required),
    bioChildren: new FormControl('', Validators.required),
    list_ages_children: new FormControl('', Validators.required),
    contraception: new FormControl(0, Validators.required),
    other_contraception: new FormControl('', Validators.required),
    age_started_period: new FormControl('', Validators.required),
    are_cycles_regular: new FormControl('', Validators.required),
    cycle_length: new FormControl('', Validators.required),
    recent_pap: new FormControl('', Validators.required),
    recent_results: new FormControl('', Validators.required),
    previous_results: new FormControl('', Validators.required),
    AIDS_Me: new FormControl(false),
    AIDS_Partner: new FormControl(false),
    AIDS_None: new FormControl(false),
    Chlamydia_Me: new FormControl(false),
    Chlamydia_Partner: new FormControl(false),
    Chlamydia_None: new FormControl(false),
    Genital_Herpes_Me: new FormControl(false),
    Genital_Herpes_Partner: new FormControl(false),
    Genital_Herpes_None: new FormControl(false),
    Genital_Sores_Me: new FormControl(false),
    Genital_Sores_Partner: new FormControl(false),
    Genital_Sores_None: new FormControl(false),
    Gonorrhea_Me: new FormControl(false),
    Gonorrhea_Partner: new FormControl(false),
    Gonorrhea_None: new FormControl(false),
    HIV_Me: new FormControl(false),
    HIV_Partner: new FormControl(false),
    HIV_None: new FormControl(false),
    NSU_Me: new FormControl(false),
    NSU_Partner: new FormControl(false),
    NSU_None: new FormControl(false),
    Penis_Discharge_Me: new FormControl(false),
    Penis_Discharge_Partner: new FormControl(false),
    Penis_Discharge_None: new FormControl(false),
    Syphilis_Me: new FormControl(false),
    Syphilis_Partner: new FormControl(false),
    Syphilis_None: new FormControl(false),
    Trichomonas_Me: new FormControl(false),
    Trichomonas_Partner: new FormControl(false),
    Trichomonas_None: new FormControl(false),
    Venereal_Warts_Me: new FormControl(false),
    Venereal_Warts_Partner: new FormControl(false),
    Venereal_Warts_None: new FormControl(false),
    Viral_Hepatitis_B_or_C_Me: new FormControl(false),
    Viral_Hepatitis_B_or_C_Partner: new FormControl(false),
    Viral_Hepatitis_B_or_C_None: new FormControl(false),
    Other_Me: new FormControl(false),
    Other_Partner: new FormControl(false),
    Other_None: new FormControl(false),
    ever_had: new FormControl(0, Validators.required),
    smoking: new FormControl('', Validators.required),
    alcohol: new FormControl('', Validators.required),
    marijuana: new FormControl('', Validators.required),
    other_drugs: new FormControl('', Validators.required),
    tattoos: new FormControl('', Validators.required),
    body_piercing: new FormControl('', Validators.required),
    acupuncture: new FormControl('', Validators.required),
    times_arrested: new FormControl('', Validators.required),
    times_convicted: new FormControl('', Validators.required),
    misdemeanors: new FormControl('', Validators.required),
    felonies: new FormControl('', Validators.required),
    incarceration: new FormControl('', Validators.required),
    most_incarceration: new FormControl('', Validators.required),
    adopted: new FormControl('', Validators.required),
    siblings: new FormControl('', Validators.required),
    maternal_grandmother: new FormControl('', Validators.required),
    maternal_grandfather: new FormControl('', Validators.required),
    paternal_grandmother: new FormControl('', Validators.required),
    paternal_grandfather: new FormControl('', Validators.required),
    mother_race: new FormControl('', Validators.required),
    mother_height: new FormControl('', Validators.required),
    mother_bone_structure: new FormControl('', Validators.required),
    father_race: new FormControl('', Validators.required),
    father_height: new FormControl('', Validators.required),
    father_bone_structure: new FormControl('', Validators.required),
    Maternal_Grandmother_race: new FormControl('', Validators.required),
    Maternal_Grandmother_height: new FormControl('', Validators.required),
    Maternal_Grandmother_bone_structure: new FormControl('', Validators.required),
    Maternal_Grandfather_race: new FormControl('', Validators.required),
    Maternal_Grandfather_height: new FormControl('', Validators.required),
    Maternal_Grandfather_bone_structure: new FormControl('', Validators.required),
    Paternal_Grandmother_race: new FormControl('', Validators.required),
    Paternal_Grandmother_height: new FormControl('', Validators.required),
    Paternal_Grandmother_bone_structure: new FormControl('', Validators.required),
    Paternal_Grandfather_race: new FormControl('', Validators.required),
    Paternal_Grandfather_height: new FormControl('', Validators.required),
    Paternal_Grandfather_bone_structure: new FormControl('', Validators.required),
    mother_eye_color: new FormControl('', Validators.required),
    mother_hair_color: new FormControl('', Validators.required),
    mother_complexion: new FormControl('', Validators.required),
    father_eye_color: new FormControl('', Validators.required),
    father_hair_color: new FormControl('', Validators.required),
    father_complexion: new FormControl('', Validators.required),
    Maternal_Grandmother_eye_color: new FormControl('', Validators.required),
    Maternal_Grandmother_hair_color: new FormControl('', Validators.required),
    Maternal_Grandmother_complexion: new FormControl('', Validators.required),
    Maternal_Grandfather_eye_color: new FormControl('', Validators.required),
    Maternal_Grandfather_hair_color: new FormControl('', Validators.required),
    Maternal_Grandfather_complexion: new FormControl('', Validators.required),
    Paternal_Grandmother_eye_color: new FormControl('', Validators.required),
    Paternal_Grandmother_hair_color: new FormControl('', Validators.required),
    Paternal_Grandmother_complexion: new FormControl('', Validators.required),
    Paternal_Grandfather_eye_color: new FormControl('', Validators.required),
    Paternal_Grandfather_hair_color: new FormControl('', Validators.required),
    Paternal_Grandfather_complexion: new FormControl('', Validators.required),
    sibling1_gender: new FormControl('', Validators.required),
    sibling1_full_half: new FormControl('', Validators.required),
    sibling1_height: new FormControl('', Validators.required),
    sibling1_bone_structure: new FormControl('', Validators.required),
    sibling2_gender: new FormControl('', Validators.required),
    sibling2_full_half: new FormControl('', Validators.required),
    sibling2_height: new FormControl('', Validators.required),
    sibling2_bone_structure: new FormControl('', Validators.required),
    sibling1_eye_color: new FormControl('', Validators.required),
    sibling1_hair_color: new FormControl('', Validators.required),
    sibling1_complexion: new FormControl('', Validators.required),
    sibling2_eye_color: new FormControl('', Validators.required),
    sibling2_hair_color: new FormControl('', Validators.required),
    sibling2_complexion: new FormControl('', Validators.required),
    mother_age: new FormControl('', Validators.required),
    mother_health: new FormControl('', Validators.required),
    mother_age_death: new FormControl('', Validators.required),
    mother_cause_death: new FormControl('', Validators.required),
    Father_age: new FormControl('', Validators.required),
    Father_health: new FormControl('', Validators.required),
    Father_age_death: new FormControl('', Validators.required),
    Father_cause_death: new FormControl('', Validators.required),
    Maternal_Grandmother_age: new FormControl('', Validators.required),
    Maternal_Grandmother_health: new FormControl('', Validators.required),
    Maternal_Grandmother_age_death: new FormControl('', Validators.required),
    Maternal_Grandmother_cause_death: new FormControl('', Validators.required),
    Maternal_Grandfather_age: new FormControl('', Validators.required),
    Maternal_Grandfather_health: new FormControl('', Validators.required),
    Maternal_Grandfather_age_death: new FormControl('', Validators.required),
    Maternal_Grandfather_cause_death: new FormControl('', Validators.required),
    Paternal_Grandmother_age: new FormControl('', Validators.required),
    Paternal_Grandmother_health: new FormControl('', Validators.required),
    Paternal_Grandmother_age_death: new FormControl('', Validators.required),
    Paternal_Grandmother_cause_death: new FormControl('', Validators.required),
    Paternal_Grandfather_age: new FormControl('', Validators.required),
    Paternal_Grandfather_health: new FormControl('', Validators.required),
    Paternal_Grandfather_age_death: new FormControl('', Validators.required),
    Paternal_Grandfather_cause_death: new FormControl('', Validators.required),
    positive_carrier: new FormControl('', Validators.required),
    Canavan_Disease: new FormControl(false),
    Cystic_Fibrosis: new FormControl(false),
    Fragile_X_Syndrome: new FormControl(false),
    Gaucher_Disease: new FormControl(false),
    Sickle_Cell_Disease: new FormControl(false),
    Spinal_Muscular_Atrophy: new FormControl(false),
    Tay_Sachs_Disease: new FormControl(false),
    Alcoholism: new FormControl(false),
    Compulsive_Behaviors: new FormControl(false),
    Drug_Abuse: new FormControl(false),
    Drug_Addict: new FormControl(false),
    Drug_Misuse: new FormControl(false),
    Gambling: new FormControl(false),
    Smoking: new FormControl(false),
    Cleft_Lip_Palate: new FormControl(false),
    Congenital_Hip_Problems: new FormControl(false),
    Club_Feet: new FormControl(false),
    Heart_Defect: new FormControl(false),
    Hearing_Problems: new FormControl(false),
    Holoprosencehpaly: new FormControl(false),
    Microcephaly: new FormControl(false),
    Neural_Tube: new FormControl(false),
    Spina_Bifida: new FormControl(false),
    Anemia: new FormControl(false),
    Bleeding_Clotting_Disorder: new FormControl(false),
    Blood_clots_or_strokes: new FormControl(false),
    Factor_V_Leiden_Thrombophilia: new FormControl(false),
    Hemophilia: new FormControl(false),
    HIV: new FormControl(false),
    Immune_Deficiency: new FormControl(false),
    Leukemia: new FormControl(false),
    Lymphoma: new FormControl(false),
    Polyarteritis_Nodose: new FormControl(false),
    Sickle_Cell_Anemia: new FormControl(false),
    Swolle_Lymph_Nodes: new FormControl(false),
    Thalassemia: new FormControl(false),
    Von_Willebrand_Disease: new FormControl(false),
    Breast: new FormControl(false),
    ColonIntestinal: new FormControl(false),
    Intestinal: new FormControl(false),
    Lung: new FormControl(false),
    Ovarian: new FormControl(false),
    Prostate: new FormControl(false),
    Skin: new FormControl(false),
    Stomach: new FormControl(false),
    Testicular: new FormControl(false),
    Thyroid: new FormControl(false),
    Uterine: new FormControl(false),
    Down_Syndrome: new FormControl(false),
    Fragile_X: new FormControl(false),
    Klinefelter_Turner: new FormControl(false),
    Appendicitis: new FormControl(false),
    Cirrhosis_of_the_Liver: new FormControl(false),
    Crohn_Disease: new FormControl(false),
    Gallstones: new FormControl(false),
    Hepatitis: new FormControl(false),
    Inflammatory_Bowel_Disease: new FormControl(false),
    Multiple_Polyps_of_the_Colon: new FormControl(false),
    Pyloric_Stenosis: new FormControl(false),
    Rectal_Disorder: new FormControl(false),
    Ulcer_of_Stomach_or_Duodenum: new FormControl(false),
    Ulcerative_Colitis: new FormControl(false),
    Ambiguous_Genitals: new FormControl(false),
    Discharge_Polycystic: new FormControl(false),
    Endometriosis: new FormControl(false),
    Hermaphroditism: new FormControl(false),
    Hypospadias: new FormControl(false),
    Low_Sperm_Count: new FormControl(false),
    Ovarian_Cysts: new FormControl(false),
    Ovarian_Syndrome: new FormControl(false),
    Pelvic_Inflammatory_Disease: new FormControl(false),
    Ruptured_Lumps_or_Cysts_in_Breast: new FormControl(false),
    Undescended_Testicle: new FormControl(false),
    Uterine_Fibroids: new FormControl(false),
    Congenital_Heart_Disease: new FormControl(false),
    Hardening_of_the_Arteries: new FormControl(false),
    Heart_Attack: new FormControl(false),
    Heart_Defects: new FormControl(false),
    Heart_Disease: new FormControl(false),
    High_Blood_Pressure: new FormControl(false),
    High_Cholesterol_Level: new FormControl(false),
    Stroke: new FormControl(false),
    Severe_Acne: new FormControl(false),
    Albinism: new FormControl(false),
    Eczema: new FormControl(false),
    Excessive_Facial_Hair: new FormControl(false),
    Infectious_Skin_Disease: new FormControl(false),
    Pigmentation_Disorders: new FormControl(false),
    Psoriasis: new FormControl(false),
    Neurofibromatosis: new FormControl(false),
    injected_drugs: new FormControl('', Validators.required),
    clotting: new FormControl('', Validators.required),
    sexual_activity: new FormControl('', Validators.required),
    sex_12: new FormControl('', Validators.required),
    exposed_preceding: new FormControl('', Validators.required),
    test_HIV: new FormControl('', Validators.required),
    unexplained_weightloss: new FormControl('', Validators.required),
    lived_with: new FormControl('', Validators.required),
    history_HepB: new FormControl('', Validators.required),
    history_HTLV: new FormControl('', Validators.required),
    incarcerated: new FormControl('', Validators.required),
    hepatitis: new FormControl('', Validators.required),
    shared_instruments: new FormControl('', Validators.required),
    past_diagnosis: new FormControl('', Validators.required),
    smallpox: new FormControl('', Validators.required),
    vaccinia_virus: new FormControl('', Validators.required),
    suspicion_WNV: new FormControl('', Validators.required),
    fever_headache: new FormControl('', Validators.required),
    close_contact_xenotransplantation: new FormControl('', Validators.required),
    received_blood: new FormControl('', Validators.required),
    Chlamydia: new FormControl('', Validators.required),
    Gonorrhea: new FormControl('', Validators.required),
    syphilis: new FormControl('', Validators.required),
    vCJD: new FormControl('', Validators.required),
    dementia: new FormControl('', Validators.required),
    Creutzfeldt_Jakob_disease: new FormControl('', Validators.required),
    pituitary_derived: new FormControl('', Validators.required),
    mater_transplant: new FormControl('', Validators.required),
    spent_UK: new FormControl('', Validators.required),
    military: new FormControl('', Validators.required),
    lived_Europe: new FormControl('', Validators.required),
    transfusion_blood: new FormControl('', Validators.required),
    bovine: new FormControl('', Validators.required),
    vaccinations: new FormControl('', Validators.required),
    donation: new FormControl('', Validators.required),
    understand: new FormControl(false),
    understand_photos: new FormControl(false),
    understand_logos: new FormControl(false),
    hear_about_us: new FormControl(0, Validators.required),
    explain_other: new FormControl('', Validators.required),
    preferred_languange: new FormControl(0, Validators.required),
    others_languange: new FormControl('', Validators.required),
    Eligibility_status: new FormControl('', Validators.required),
    Coordinator: new FormControl('', Validators.required)
  });

  onSubmit() {
    if (this.form.valid) {
      console.log("Form Submitted!", this.form.value);
      /* this.Submit(this.service.form.value).subscribe((result) => {
        console.warn("Result is here", result);
      }) */
    }
  }

  TotalRow: number;
  Form: FormGroup;
  Form2: FormGroup;

  constructor(private _fb: FormBuilder) { }

  ngOnInit(): void {
    this.Form = this._fb.group({
      list_medications: this._fb.array([this.initListMedications()],)
    });
    this.Form2 = this._fb.group({
      list_surgical_procedures: this._fb.array([this.initListSurgicalProcedures()],)
    });
  }

  initListSurgicalProcedures() {
    return this._fb.group({
      no: [''],
      date: [''],
      procedure: [''],
      reason: [''],
      outcome: ['']
    });
  }

  initListMedications() {
    return this._fb.group({
      no: [''],
      medication: [''],
      how_often: [''],
      reason: ['']
    });
  }

  addNewRow2() {
    const control = <FormArray>this.Form2.controls['list_surgical_procedures'];
    control.push(this.initListSurgicalProcedures());
  }

  addNewRow() {
    const control = <FormArray>this.Form.controls['list_medications'];
    control.push(this.initListMedications());
  }

  deleteRow2(index: number) {
    const control = <FormArray>this.Form2.controls['list_surgical_procedures'];
    if (control != null) {
      this.TotalRow = control.value.length;
    }
    if (this.TotalRow > 1) {
      control.removeAt(index);
    } else {
      alert('One record is mandatory.');
      return false;
    }
  }

  deleteRow(index: number) {
    const control = <FormArray>this.Form.controls['list_medications'];
    if (control != null) {
      this.TotalRow = control.value.length;
    }
    if (this.TotalRow > 1) {
      control.removeAt(index);
    } else {
      alert('One record is mandatory.');
      return false;
    }
  }

}